### ISSUE TITLE
Relative URLs not expanded

### ISSUE THREAD

**Issue by badboy** [swanson/stringer#379] opened 2015-06-30 21:42 UTC
Posts from http://githubengineering.com/atom.xml result in broken links, because they are relative and are not expanded.

My stringer is currently on a state from last September, so this might very well be fixed already, but I got no time to check right now. I will upgrade this week and then see again unless someone already knows for sure if this is a still-existing bug.

**Comment by Koronen** [comment] 2015-07-02 10:22
Links from the GitHub Engineering blog work fine for me. I'm running 64ab6e81c296a5d4857be0108a949969da115943 (2015-05-01).

**Comment by badboy** [comment] 2015-07-02 11:04
Removed the feed, updated Stringer and re-added the feed. Story headline links to `http:/scripts-to-rule-them-all/` which is wrong.

**Comment by Koronen** [comment] 2015-07-02 11:21
Oh, I didn't look at the headlines, I just checked links in the post bodies. I see what you mean now.

**Comment by Koronen** [comment] 2015-07-02 15:35
This is possibly another case of #222, caused by the use of relative URLs for *all* `link` elements, even for the base ones nested directly under `feed`. Without a base absolute URL, [Feedjira](https://github.com/feedjira/feedjira), which we use for parsing, cannot expand the URLs.

I'm closing this, as this is not an issue specific to Stringer, but rather with the feed itself. It [doesn't pass W3C's Feed Validation Service](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fgithubengineering.com%2Fatom.xml) at the time of this writing.

For reference, here's the start of the feed in question:
```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
 <title>GitHub Engineering</title>
 <link href="/atom.xml" rel="self"/>
 <link href=""/>
 <updated>2015-07-01T01:56:14+00:00</updated>
 <id></id>
 <author>
   <name>GitHub Engineering</name>
 </author>

 
 <entry>
   <title>Scripts to Rule Them All</title>
   <link href="/scripts-to-rule-them-all/"/>
   <updated>2015-06-30T00:00:00+00:00</updated>
   <id>/scripts-to-rule-them-all</id>
```

**Closed by Koronen** 2015-07-02 15:35 UTC

**Comment by badboy** [comment] 2015-07-02 15:54
Ok, thanks. Will report it back upstream then.

**Comment by badboy** [comment] 2015-07-02 16:15
FYI: it's fixed. https://twitter.com/aroben/status/616641212980817924
